// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	products "github.com/Rahmanwghazi/Monefy/business/products"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetProductByID provides a mock function with given fields: id
func (_m *Repository) GetProductByID(id string) (products.ProductDomain, error) {
	ret := _m.Called(id)

	var r0 products.ProductDomain
	if rf, ok := ret.Get(0).(func(string) products.ProductDomain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(products.ProductDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
