// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	users "github.com/Rahmanwghazi/Monefy/business/users"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Edit provides a mock function with given fields: domain
func (_m *Repository) Edit(domain *users.UserDomain) (users.UserDomain, error) {
	ret := _m.Called(domain)

	var r0 users.UserDomain
	if rf, ok := ret.Get(0).(func(*users.UserDomain) users.UserDomain); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(users.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*users.UserDomain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Signin provides a mock function with given fields: username
func (_m *Repository) Signin(username string) (users.UserDomain, error) {
	ret := _m.Called(username)

	var r0 users.UserDomain
	if rf, ok := ret.Get(0).(func(string) users.UserDomain); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(users.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Signup provides a mock function with given fields: domain
func (_m *Repository) Signup(domain *users.UserDomain) (users.UserDomain, error) {
	ret := _m.Called(domain)

	var r0 users.UserDomain
	if rf, ok := ret.Get(0).(func(*users.UserDomain) users.UserDomain); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(users.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*users.UserDomain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
